import { Injectable } from '@nestjs/common';
import { randomBytes, timingSafeEqual } from 'node:crypto';
import {
  API_KEY_SECRET_BYTES,
  API_KEY_STORED_PREFIX_LENGTH,
  API_KEY_TOKEN_PREFIX,
  hashApiKey,
} from '../../common/security/api-key';
import { NotFoundError, ValidationError } from '../../common/errors/domain-errors';
import { ApiKeysStore, type ApiKeyListRow, type ApiKeyRow } from '../../store/api-keys.store';
import type { AuthenticatedAdmin } from './guards/admin.guard';
import { AdminRbacService } from './admin-rbac.service';
import { AdminAuditService } from './admin-audit.service';

/**
 * Machine credentials for the admin API — issue, list, revoke.
 *
 * ── This is the ONLY place a plaintext key exists ──────────────────────────
 *
 * `create` generates it, hashes it, hands the plaintext back to its caller
 * ONCE, and never writes it anywhere. `ApiKeysStore` moves hashes and nothing
 * else. That split is the same one `settings.service.ts` and
 * `SmtpConfigService` use for the SMTP password, and it exists so "what could
 * read a live credential" is answerable by finding one file.
 *
 * ── The token format, and why the prefix is not a secret ───────────────────
 *
 *     oxs_live_<43 chars of base64url>
 *      │    │    └── 32 bytes from randomBytes: the secret
 *      │    └── environment marker, so a staging key is visibly not production
 *      └── vendor tag, so a leaked key is greppable and attributable
 *
 * `prefix` stores the first 16 characters. That is the vendor tag, the
 * environment, and a few characters of entropy — enough for an operator to
 * tell two keys apart in a list, and to match a key found in a log against a
 * row, while being far too little to authenticate with.
 *
 * Secret scanners key on fixed prefixes exactly like this one; a bare random
 * string in a public repository is invisible to them.
 */

/** What `create` returns — the ONLY moment the plaintext is available. */
export interface IssuedApiKey {
  row: ApiKeyRow;
  /** Shown once. Never stored, never recoverable, never logged. */
  plaintext: string;
}

@Injectable()
export class ApiKeysService {
  constructor(
    private readonly store: ApiKeysStore,
    private readonly rbac: AdminRbacService,
    private readonly audit: AdminAuditService,
  ) {}

  async list(): Promise<ApiKeyListRow[]> {
    return this.store.list();
  }

  /**
   * Issue a key. The plaintext in the return value is the only copy.
   *
   * ── Anti-escalation, via the SAME check roles use ──────────────────────────
   *
   * `assertGrantable` is reused rather than reimplemented, and that is the
   * security-critical line in this method. Without it an API key would be a
   * trivial privilege-escalation device: a sub-admin holding `users.view` could
   * mint a key holding `withdrawals.approve` and then call the admin API as
   * that key. The rule is the one that already governs roles — you cannot grant
   * what you do not hold, and only a master admin may grant `*`.
   */
  async create(
    actor: AuthenticatedAdmin,
    input: { name: string; permissions: string[]; expiresAt: Date | null },
  ): Promise<IssuedApiKey> {
    const name = input.name.trim();
    if (!name) throw new ValidationError('A key name is required.');

    if (input.permissions.length === 0) {
      /*
       * Refused rather than allowed as a no-op. A key with no permissions
       * authenticates and can then do nothing, which reads to whoever installed
       * it as "the integration is broken" — a support ticket generated by a
       * form nobody filled in.
       */
      throw new ValidationError(
        'Select at least one permission. A key with none can authenticate but do nothing.',
      );
    }

    await this.rbac.assertGrantable(actor, input.permissions);

    if (input.expiresAt && input.expiresAt.getTime() <= Date.now()) {
      throw new ValidationError('The expiry date must be in the future.');
    }

    const plaintext = `${API_KEY_TOKEN_PREFIX}${randomBytes(API_KEY_SECRET_BYTES).toString('base64url')}`;

    /*
     * Snapshot the creator's TERRITORY onto the key (D-45 / #7). A key
     * authenticates with this scope, not with unrestricted sight, so a
     * tag-scoped admin cannot mint a key that escapes their territory. Empty
     * tags means unrestricted, so an unrestricted admin's key still sees the
     * whole book — the reporting-job case. Snapshot, not a live join: the key
     * keeps its territory when the creator's changes and after the creator is
     * deleted (`createdBy` is `set null`), mirroring `admin_invites`.
     */
    const scopedTagIds = actor.clientScope.unrestricted ? null : [...actor.clientScope.tagIds];
    const seesUntriaged = actor.clientScope.unrestricted
      ? true
      : (actor.clientScope.includesUntriaged ?? false);

    const row = await this.store.create({
      name,
      secretHash: hashApiKey(plaintext),
      prefix: plaintext.slice(0, API_KEY_STORED_PREFIX_LENGTH),
      permissions: input.permissions,
      createdBy: actor.id,
      scopedTagIds,
      seesUntriaged,
      expiresAt: input.expiresAt,
    });

    /*
     * The PERMISSIONS are recorded, the key is not — not the plaintext, not the
     * hash, not a longer prefix than the list screen already shows.
     *
     * The audit log is append-only by trigger and readable by any unrestricted
     * admin, so a credential written here could never be revoked from it. What
     * an auditor needs is what this key can DO and who issued it, which is
     * exactly what is recorded.
     */
    this.audit.record(actor.id, 'api_key.create', 'api_key', row.id, {
      name: row.name,
      prefix: row.prefix,
      permissions: row.permissions,
      expiresAt: row.expiresAt?.toISOString() ?? null,
    });

    return { row, plaintext };
  }

  /**
   * Revoke a key. Immediate — the guard checks `revoked_at` on every request.
   *
   * The row is kept rather than deleted: the audit trail points at this id, and
   * "revoked last Tuesday" is what an operator investigating an incident needs.
   */
  async revoke(actor: AuthenticatedAdmin, id: string): Promise<ApiKeyRow> {
    const revoked = await this.store.revoke(id);
    if (revoked) {
      this.audit.record(actor.id, 'api_key.revoke', 'api_key', id, {
        name: revoked.name,
        prefix: revoked.prefix,
      });
      return revoked;
    }

    /*
     * `revoke` returning null means either "no such key" or "already revoked",
     * and the two need different answers. Re-reading tells them apart — and
     * makes revoking an already-revoked key SUCCEED silently rather than error:
     * the caller's intent is satisfied, and no second audit row is written for
     * a change that did not happen.
     */
    const existing = await this.store.findById(id);
    if (!existing) throw new NotFoundError('API key not found.');
    return existing;
  }

  /**
   * Constant-time comparison of two hashes.
   *
   * Unused by the current lookup — the guard finds the row by an indexed
   * equality on the hash, which is a database operation and not a place a
   * timing signal is meaningfully exploitable. Exported for the day a caller
   * compares two hashes in JavaScript, so that caller does not reach for `===`.
   */
  static hashesEqual(a: string, b: string): boolean {
    const left = Buffer.from(a, 'utf8');
    const right = Buffer.from(b, 'utf8');
    if (left.length !== right.length) return false;
    return timingSafeEqual(left, right);
  }
}
