import { ApiProperty } from '@nestjs/swagger';
import { ClientField, NotClientField } from '../../../common/security/client-field.decorator';

// Response DTOs for the client-facing wallet endpoints.
//
// These exist because `WalletController` carried no @ApiOkResponse, so
// `operations['WalletController_myWallets']` generated as `content?: never` and
// the client portal had nothing to alias. It hand-wrote the shapes instead — and
// got `GET /wallet/ledger` wrong, declaring a bare array where the endpoint
// actually returns the paginated envelope below. That is the drift these DTOs
// remove (API-CONTRACTS Part C).
//
// Every monetary field is `type: 'string'` on purpose (ARCHITECTURE §6.1):
// NUMERIC(28,8) does not survive a JS number, so money crosses this boundary as a
// decimal string and the generated TypeScript must say `string`.

/*
 * ── `currency` IS A CODE, NOT AN ENUM ────────────────────────────────────────
 *
 * This declared `enum: ['USD', 'USDT']`, which reintroduced the very thing the
 * schema deliberately removed: currencies were a `pgEnum` once, and that made
 * "what money can this platform hold" a deploy. They are a TABLE now — see the
 * note on `currencies` in schema.ts — and an operator adds one from the admin
 * screen.
 *
 * The cost was not theoretical. The portal aliased the generated union as
 * `WalletCurrency`, its wallet carousel typed its entries by it, and a client
 * holding six wallets could only ever be shown two — the dashboard counted six
 * from the same endpoint, so the two screens disagreed about the same client.
 *
 * A plain string, described by where the valid values come from. The foreign
 * key on `wallets.currency` is what actually constrains it, and
 * `CurrenciesService.assertUsable` is what refuses an unknown or disabled one
 * on every write path.
 */
export class WalletDto {
  @ApiProperty() id: string;
  @ApiProperty({
    example: '4f7kq2nm8xcb',
    description:
      'Human-friendly wallet number — 12 lowercase Crockford base32 chars. ' +
      'Display and support reference only; `id` remains the key.',
  })
  walletNumber: string;

  @ApiProperty({ type: 'integer' }) userId: number;

  /**
   * What this wallet is CALLED.
   *
   * Sent from the server rather than built in each app, so the portal, the
   * admin console and a CSV export cannot disagree about what one wallet is
   * named. Generated by the database from `currency` and `kind`, so it is
   * correct by construction on every row including the backfilled ones.
   *
   * ENGLISH and canonical — the string an operator greps for and support
   * quotes. A localised UI may render its own label from `currency` and `kind`
   * (both are here for exactly that), and should: freezing one language into
   * the database would make this wrong for every other reader.
   */
  @ApiProperty({
    example: 'USD Wallet',
    description:
      'The wallet name — "<CURRENCY> Wallet" for a main wallet, "Commission Wallet" for a ' +
      "partner's earnings wallet. Server-generated from `currency` and `kind`; never writable. " +
      'English and canonical — a localised UI should build its own label from `currency` and ' +
      '`kind` rather than translating this string.',
  })
  name: string;

  @ApiProperty({
    description:
      'A currency CODE from `GET /currencies`, not a fixed set — currencies are operator data.',
    example: 'USD',
  })
  currency: string;

  /**
   * WHAT this wallet is for — `main` or `commission`.
   *
   * ## `GET /wallet` only ever returns `main`, so why send it at all
   *
   * Because this DTO is ALSO what `GET /ib/overview` returns commission wallets
   * as, and a screen holding both lists must not have to remember which array
   * it took a card from. The field travels with the wallet rather than with the
   * request that fetched it, so a card rendered from either list can label
   * itself and cannot be mislabelled by being passed to the wrong component.
   *
   * A client who is not a partner sees only `main` and can ignore this.
   */
  @ApiProperty({
    enum: ['main', 'commission'],
    description:
      "`GET /wallet` returns `main` only — a commission wallet is a partner's earnings and " +
      'appears solely on GET /ib/overview. It cannot be deposited to, withdrawn from, or moved ' +
      'to a trading account; POST /ib/wallet/transfer moves it into the main wallet first.',
  })
  kind: 'main' | 'commission';

  @ApiProperty({ type: 'string', example: '700.00000000', description: 'Decimal string (§6.1).' })
  balance: string;

  @ApiProperty({
    type: 'string',
    example: '0.00000000',
    description: 'Reserved against pending withdrawals.',
  })
  onHold: string;

  @ApiProperty({
    type: 'string',
    example: '700.00000000',
    description: 'balance − onHold, computed server-side so both sides agree.',
  })
  available: string;

  @ApiProperty() createdAt: Date;
}

/**
 * A single append-only ledger row.
 *
 * Defined here, in the module that owns the ledger, and re-exported by
 * modules/admin/dto/responses.dto.ts for the ADM-13 admin view — admin already
 * depends on wallet (WalletModule, WalletService), so this is the correct
 * direction. It was briefly declared in both places, which is a silent schema
 * collision: Swagger keys by class name and one definition overwrites the other.
 */
/**
 * ⚠️ THIS NOW CARRIES CLIENT IDENTITY, AND IT DID NOT UNTIL 14 Sep 2026.
 *
 * It was `@NoClientFields('… the person who owns it is not projected here')`,
 * which was an accurate description and a bad outcome: ADM-13 rendered
 * `r.userId` — a raw uuid in monospace — in its column headed "Client", on the
 * screen an operator opens precisely to ask WHOSE MONEY THIS IS. Its siblings
 * `/wallets` and `/trading-accounts` have shown a named Owner all along, so the
 * ledger was inconsistent with them rather than deliberately anonymous.
 *
 * The identity is masked on the ADMIN path and untouched on the PORTAL one, by
 * `FieldMaskInterceptor`, which keys on `req.admin` rather than on the route.
 * That asymmetry is deliberate and is the case its own docblock calls exposure
 * 8: the same shape must be masked for an administrator whose role hides a
 * field, and left alone for a client reading their own ledger, where an
 * administrator's mask has no standing.
 */
export class LedgerEntryDto {
  @NotClientField('an identifier addressing the record, not an attribute of the person behind it')
  @ApiProperty()
  id: string;

  @NotClientField('an identifier addressing the record, not an attribute of the person behind it')
  @ApiProperty()
  walletId: string;
  @NotClientField('an identifier addressing the record, not an attribute of the person behind it')
  @ApiProperty({
    example: '4f7kq2nm8xcb',
    description: 'The wallet’s human-friendly number — display only; `walletId` is the key.',
  })
  walletNumber: string;

  @NotClientField('an identifier addressing the record, not an attribute of the person behind it')
  @ApiProperty()
  userId: number;
  /*
   * Nullable, and the LEFT join behind them is the reason. `ledger_entries` is
   * append-only: an entry whose client row has since gone must still appear,
   * because a reconciliation that silently drops rows is worse than one naming
   * an id it cannot resolve. So the screen falls back to the uuid rather than
   * the row vanishing.
   */
  /**
   * The client's Portal ID. NOT masked: it identifies the client without
   * revealing anything about them, which makes it the identifier a masked
   * reader still gets (this row used to fall back to the UUID for that).
   */
  @NotClientField('an identifier addressing the record, not an attribute of the person behind it')
  @ApiProperty({ type: Number, nullable: true, example: 1000001 })
  userPortalId: number | null;

  @ClientField('client.firstName')
  @ApiProperty({ type: 'string', nullable: true })
  userFirstName: string | null;

  @ClientField('client.lastName')
  @ApiProperty({ type: 'string', nullable: true })
  userLastName: string | null;

  @ClientField('client.email')
  @ApiProperty({ type: 'string', nullable: true })
  userEmail: string | null;

  @NotClientField('a movement of money, not an attribute of the person it belongs to')
  @ApiProperty({ description: 'Signed monetary value as a string' })
  amount: string;
  @NotClientField('a movement of money, not an attribute of the person it belongs to')
  @ApiProperty({ description: 'Running balance after this entry, as a string' })
  balanceAfter: string;
  @NotClientField('a movement of money, not an attribute of the person it belongs to')
  @ApiProperty({
    enum: ['deposit', 'withdrawal', 'commission', 'rebate', 'payout', 'adjustment'],
  })
  entryType: string;
  @NotClientField('an identifier addressing the record, not an attribute of the person behind it')
  @ApiProperty()
  referenceType: string;

  @NotClientField('an identifier addressing the record, not an attribute of the person behind it')
  @ApiProperty()
  referenceId: string;
  @NotClientField('a movement of money, not an attribute of the person it belongs to')
  @ApiProperty({ description: 'A currency code — see WalletDto.', example: 'USD' })
  currency: string;

  @NotClientField('when the movement happened, not who it belongs to')
  @ApiProperty()
  createdAt: Date;
}

/**
 * `GET /wallet/ledger` and `GET /admin/ledger` are paginated, unlike
 * `GET /wallet` which returns a bare array. The portal hand-wrote the client
 * ledger call as returning a bare array, which this makes impossible.
 */
/*
 * No `@NoClientFields` here any more, and its absence is required rather than
 * an omission: this wraps `LedgerEntryDto`, which now carries client identity,
 * and GUARD 1 of `client-field-coverage.spec.ts` refuses an exempt class that
 * references one holding client fields. Keeping the old exemption would have
 * been a false statement the census exists to catch.
 */
export class LedgerListResponseDto {
  @NotClientField(
    'the page of movements; whose data each row holds is declared on LedgerEntryDto itself',
  )
  @ApiProperty({ type: [LedgerEntryDto] })
  items: LedgerEntryDto[];
  /**
   * Pass back as `?cursor=` for the next page; `null` on the last (R-2.4).
   *
   * The ledger is append-only and never stops growing, so it reaches the depth
   * where OFFSET hurts before any other list — and it is the one used FOR
   * reconciliation, where a silently skipped entry means balancing against the
   * wrong set of rows.
   */
  @NotClientField('a paging control, not an attribute of any person')
  @ApiProperty({ type: String, nullable: true })
  nextCursor: string | null;

  @NotClientField('a paging control, not an attribute of any person')
  @ApiProperty({ description: 'Total matching entries, ignoring pagination.' })
  total: number;

  @NotClientField('a paging control, not an attribute of any person')
  @ApiProperty()
  page: number;

  @NotClientField('a paging control, not an attribute of any person')
  @ApiProperty()
  limit: number;

  /*
   * Which client columns THIS reader's role hides. A statement ABOUT the mask,
   * not masked data — so it survives `FieldMaskInterceptor` and is what lets
   * the screen say once, above the table, that a column is hidden by policy
   * rather than empty. Optional because the PORTAL shares this shape and has no
   * administrator mask to report.
   */
  @NotClientField('names which fields are hidden; it holds no client data itself')
  @ApiProperty({ type: [String], required: false })
  maskedFields?: string[];
}

/** One movement on a statement, with the balance it left the wallet at. */
export class StatementLineDto {
  @ApiProperty() id: string;
  @ApiProperty() createdAt: Date;
  @ApiProperty({
    enum: ['deposit', 'withdrawal', 'commission', 'rebate', 'payout', 'adjustment', 'transfer'],
  })
  entryType: string;
  @ApiProperty({ example: 'transaction' }) referenceType: string;
  @ApiProperty() referenceId: string;
  @ApiProperty({ description: 'Signed decimal string: positive credits, negative debits.' })
  amount: string;
  @ApiProperty({ description: 'Wallet balance after this line, as stored by the ledger.' })
  balanceAfter: string;
  @ApiProperty({ type: String, nullable: true, description: 'Payment rail name, if any.' })
  methodName: string | null;
  @ApiProperty({
    type: String,
    nullable: true,
    description: 'Payment provider; `manual_admin` for money the team placed by hand.',
  })
  provider: string | null;
  @ApiProperty({ type: String, nullable: true, description: 'MT5 login, for a transfer line.' })
  tradingAccountLogin: string | null;
  @ApiProperty({
    type: String,
    nullable: true,
    description: 'Trading account name, for a transfer line.',
  })
  tradingAccountName: string | null;
  @ApiProperty({
    type: String,
    nullable: true,
    enum: ['wallet_to_account', 'account_to_wallet'],
  })
  transferDirection: string | null;
}

/**
 * `GET /wallet/statement` — one wallet over one period, reconciling:
 * opening + credits − debits = closing, and every line carries the running
 * balance the ledger stored for it.
 */
export class StatementDto {
  @ApiProperty() walletId: string;
  @ApiProperty() walletNumber: string;
  @ApiProperty({ example: 'USD' }) currency: string;
  @ApiProperty({ example: '2026-09-01' }) from: string;
  @ApiProperty({ example: '2026-09-30' }) to: string;
  @ApiProperty({ description: 'Balance at the start of `from`.' }) openingBalance: string;
  @ApiProperty({ description: 'Balance at the end of `to`.' }) closingBalance: string;
  @ApiProperty() totalCredits: string;
  @ApiProperty({ description: 'Positive: the sum of money that left.' }) totalDebits: string;
  @ApiProperty({ type: [StatementLineDto] }) lines: StatementLineDto[];
  @ApiProperty({ description: 'True when the period held more lines than one statement returns.' })
  truncated: boolean;
  @ApiProperty() generatedAt: Date;
}
