#!/usr/bin/env bash
#
# Builds a fresh Ubuntu server into an OxShare host, exactly as both production
# servers were built on 5 Oct 2026 (DEPLOY-PLAYBOOK §2–§3). Idempotent: safe to
# re-run on a server that already has it. Run as ROOT, from your machine:
#
#   ssh-copy-id -i ~/.ssh/id_ed25519.pub root@<ip>            # once, needs the root password
#   ssh root@<ip> 'ROLE=api ADMIN_KEY="$(cat)" ...' ...        # see DEPLOYMENT.md, "Replacing a server"
#
# Inputs (environment):
#   ROLE           api | web       api = the backend server (adds WireGuard to the bridge)
#   ADMIN_KEY      public key      your own key, for `ssh oxshare-api` / `ssh oxshare-web`
#   CI_KEY         public key      the GitHub Actions deploy key (~/.ssh/oxshare_deploy.pub)
#   BRIDGE_IP      api only        the Windows bridge server's public IP (WireGuard accepts only it)
#   BRIDGE_PUBKEY  api only, opt.  the bridge tunnel's PUBLIC key; without it the peer is left out
#   BRIDGE_PORT    api only, opt.  the bridge tunnel's ListenPort (default 51820), so THIS side can
#                                  re-open the tunnel too, in seconds, after either side restarts
#
# After it: reboot if it says so, then run the HTTP/3 check (DEPLOY-PLAYBOOK §7).
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

: "${ROLE:?ROLE must be api or web}"
: "${ADMIN_KEY:?ADMIN_KEY (your public key) is required}"
: "${CI_KEY:?CI_KEY (the deploy public key) is required}"
case "$ROLE" in api | web) ;; *) echo "ROLE must be api or web" >&2; exit 1 ;; esac
[ "$ROLE" = web ] || : "${BRIDGE_IP:?BRIDGE_IP is required for ROLE=api}"

echo "== updates (old config files kept, never a prompt)"
apt-get update -q >/dev/null
apt-get -y -q -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold upgrade >/dev/null

echo "== timezone + 2G swap (VPSes ship without; a build would be OOM-killed)"
timedatectl set-timezone UTC
if ! swapon --show | grep -q /swapfile; then
  [ -f /swapfile ] || fallocate -l 2G /swapfile
  chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile
fi
grep -q '^/swapfile ' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab

echo "== docker + log rotation (unbounded json logs fill the disk in months)"
command -v docker >/dev/null || curl -fsSL https://get.docker.com | sh >/dev/null
mkdir -p /etc/docker
cat > /etc/docker/daemon.json <<'JSON'
{ "log-driver": "json-file", "log-opts": { "max-size": "20m", "max-file": "5" } }
JSON
systemctl restart docker && systemctl enable docker >/dev/null 2>&1

echo "== deploy user: keys only, in the docker group; root mirrors the same keys"
id deploy >/dev/null 2>&1 || adduser --disabled-password --gecos "" deploy >/dev/null
usermod -aG docker deploy
install -d -m 700 -o deploy -g deploy /home/deploy/.ssh
printf '%s\n' "$ADMIN_KEY" "$CI_KEY" > /home/deploy/.ssh/authorized_keys
chown deploy:deploy /home/deploy/.ssh/authorized_keys && chmod 600 /home/deploy/.ssh/authorized_keys
install -d -m 700 /root/.ssh && touch /root/.ssh/authorized_keys
for k in "$ADMIN_KEY" "$CI_KEY"; do grep -qxF "$k" /root/.ssh/authorized_keys || echo "$k" >> /root/.ssh/authorized_keys; done
chmod 600 /root/.ssh/authorized_keys

echo "== firewall: 22, 80, 443 tcp + 443 udp (HTTP/3). Docker-published ports bypass UFW;"
echo "   only Caddy publishes, and that is the real boundary (DEPLOY-PLAYBOOK §2)"
apt-get install -y -q ufw >/dev/null
ufw default deny incoming >/dev/null && ufw default allow outgoing >/dev/null
for rule in 22/tcp 80/tcp 443/tcp 443/udp; do ufw allow "$rule" >/dev/null; done
ufw --force enable >/dev/null

echo "== fail2ban (root keeps password login by design) + unattended security upgrades"
apt-get install -y -q fail2ban unattended-upgrades >/dev/null
systemctl enable --now fail2ban >/dev/null 2>&1
dpkg-reconfigure -f noninteractive unattended-upgrades

if [ "$ROLE" = api ]; then
  echo "== WireGuard to the bridge: this server 10.8.0.1, the bridge 10.8.0.2"
  apt-get install -y -q wireguard >/dev/null
  umask 077
  # A replacement server gets a NEW key pair: the bridge's tunnel must then be
  # given the new public key printed at the end (DEPLOYMENT.md).
  [ -f /etc/wireguard/wg0.key ] || wg genkey > /etc/wireguard/wg0.key
  wg pubkey < /etc/wireguard/wg0.key > /etc/wireguard/wg0.pub
  # A re-run without BRIDGE_PUBKEY keeps the peer already configured, so running
  # this script again can never silently cut the bridge off.
  if [ -z "${BRIDGE_PUBKEY:-}" ] && [ -f /etc/wireguard/wg0.conf ]; then
    BRIDGE_PUBKEY=$(awk '/^\[Peer\]/{p=1} p && /^PublicKey/{print $3; exit}' /etc/wireguard/wg0.conf)
  fi
  {
    echo "# OxShare backend <-> MT5 bridge. Generated by deploy/provision-server.sh."
    echo "[Interface]"
    echo "Address = 10.8.0.1/24"
    echo "ListenPort = 51820"
    # Inline (the file is root-only, 0600), never via PostUp: `wg syncconf` rebuilds the
    # interface from this file, and a key loaded by a hook is silently DROPPED by it.
    # That took the tunnel down for 41 minutes on 6 Oct 2026.
    echo "PrivateKey = $(cat /etc/wireguard/wg0.key)"
    if [ -n "${BRIDGE_PUBKEY:-}" ]; then
      echo ""
      echo "# The Windows bridge server. BOTH sides can open the tunnel: it dials in"
      echo "# (PersistentKeepalive on its side) and this side dials its fixed ListenPort,"
      echo "# so a restart on either side recovers in seconds, not at the next rekey."
      echo "[Peer]"
      echo "PublicKey = $BRIDGE_PUBKEY"
      echo "Endpoint = $BRIDGE_IP:${BRIDGE_PORT:-51820}"
      echo "AllowedIPs = 10.8.0.2/32"
      echo "PersistentKeepalive = 25"
    fi
  } > /etc/wireguard/wg0.conf
  chmod 600 /etc/wireguard/wg0.conf
  systemctl enable wg-quick@wg0 >/dev/null 2>&1 && systemctl restart wg-quick@wg0
  ufw allow from "$BRIDGE_IP" to any port 51820 proto udp comment 'WireGuard: MT5 bridge only' >/dev/null

  # Caddy publishes the bridge's door on 10.8.0.1:8080, which exists only once
  # wg0 is up: Docker must start after the tunnel or that bind fails at boot.
  mkdir -p /etc/systemd/system/docker.service.d
  cat > /etc/systemd/system/docker.service.d/after-wireguard.conf <<'UNIT'
[Unit]
Wants=wg-quick@wg0.service
After=wg-quick@wg0.service
UNIT
  systemctl daemon-reload
fi

echo "== check"
sshd -T | grep -E '^(passwordauthentication|permitrootlogin|pubkeyauthentication) '
echo "swap: $(swapon --show --noheadings | awk '{print $3}') | $(docker --version)"
ufw status | grep -E 'ALLOW' | grep -v v6
[ -f /var/run/reboot-required ] && echo ">>> REBOOT REQUIRED: run 'reboot', then reconnect."
[ "$ROLE" = api ] && echo ">>> This server's WireGuard PUBLIC key (give it to the bridge's tunnel): $(cat /etc/wireguard/wg0.pub)"
echo "done."
