import { FieldValidationError } from '../errors/domain-errors';
import { phoneProblem, toE164 } from '../profile/client-profile';
import {
  hasControlCharacter,
  PROOF_FIELD_ID_PATTERN,
  PROOF_FIELD_LIMITS,
  PROOF_FIELD_TYPES,
  type ProofFieldType,
} from './proof-fields';

/**
 * Where the client PAYS an offline deposit — the pure rules (0199).
 *
 * The other half of `proof-fields.ts`. Those are questions the client answers;
 * these are facts the BROKER states: the phone the money goes to, the account
 * name, an IBAN. The admin defines them per method
 * (`payment_methods.pay_to_fields`) and the client reads them on the deposit
 * screen, with a Copy button, before sending the money.
 *
 * They are what `pay_to`/`instructions` were until 0042 dropped them (see the
 * note on `payment_methods` in `schema.ts`): an offline method without them gives
 * a reference and no destination.
 *
 * Three rules carry the design:
 *
 * - **Only on an offline route.** A method whose deposit channel redirects to a
 *   provider's page never shows them — the client is sent to the provider, and a
 *   number beside that page would be a second destination. The configuration is
 *   kept, inert, like a gateway method's proof fields.
 * - **A deposit keeps what it was shown.** Filing copies the shown details onto
 *   the transaction (`transactions.pay_to_details`), immutable by trigger. The
 *   admin may change the number tomorrow; the desk still sees which number THIS
 *   client was told to send to.
 * - **A phone is stored as E.164**, through the profile's own `toE164`, so the
 *   client copies a number that dials from anywhere.
 *
 * No Nest, no Drizzle: `schema.ts` types its columns with these.
 */

/** One detail an offline method SHOWS the client, as the admin configured it. */
export interface PayToField {
  /** Permanent — `f_` + base-36, generated by the console. */
  id: string;
  /** What the client reads beside the value ("Send to"). */
  label: string;
  type: ProofFieldType;
  /** The broker's own value — a phone is stored E.164. */
  value: string;
  /** Shown to clients. A hidden detail is kept (and restorable) but never shown. */
  enabled: boolean;
  /** One line under the value, e.g. "Whish account in the name of OxShare". */
  hint?: string;
  /** The label in Arabic. Absent = not translated. */
  labelAr?: string;
  /** The hint in Arabic. Absent = not translated. */
  hintAr?: string;
}

/** What a client is shown for one detail — no `enabled`, which is the desk's business. */
export interface ShownPayToField {
  id: string;
  label: string;
  labelAr: string | null;
  type: ProofFieldType;
  value: string;
  hint: string | null;
  hintAr: string | null;
}

/** One detail as it was SHOWN when a deposit was filed — kept on the transaction. */
export interface PayToDetail {
  fieldId: string;
  label: string;
  labelAr?: string;
  type: ProofFieldType;
  value: string;
}

export interface PayToFieldInput {
  id: string;
  label: string;
  type: string;
  value: string;
  enabled?: boolean;
  hint?: string | null;
  labelAr?: string | null;
  hintAr?: string | null;
}

/**
 * The configuration as stored, or every refusal keyed `payToFields.<i>.<prop>`.
 *
 * The value is REQUIRED: a detail with nothing to show is a heading over an
 * empty line, which on a payment screen reads as "send it nowhere".
 */
export function normalisePayToFields(input: readonly PayToFieldInput[]): PayToField[] {
  const errors: Record<string, string> = {};
  if (input.length > PROOF_FIELD_LIMITS.fields) {
    errors['payToFields'] = `A method can show at most ${PROOF_FIELD_LIMITS.fields} details.`;
  }
  const ids = new Set<string>();
  const labels = new Set<string>();
  const fields: PayToField[] = [];

  input.forEach((raw, i) => {
    const at = `payToFields.${i}`;
    const label = raw.label.trim();
    const value = raw.value.trim();
    const hint = raw.hint?.trim() ?? '';
    const labelAr = raw.labelAr?.trim() ?? '';
    const hintAr = raw.hintAr?.trim() ?? '';

    if (!PROOF_FIELD_ID_PATTERN.test(raw.id)) {
      errors[`${at}.id`] = 'This detail has an invalid id. Remove it and add it again.';
    } else if (ids.has(raw.id)) {
      errors[`${at}.id`] = 'Two details share one id. Remove one and add it again.';
    }
    ids.add(raw.id);

    if (label === '' || label.length > PROOF_FIELD_LIMITS.label) {
      errors[`${at}.label`] = `Name each detail in 1 to ${PROOF_FIELD_LIMITS.label} characters.`;
    } else if (labels.has(label.toLowerCase())) {
      errors[`${at}.label`] = `Two details are called “${label}”. Give each its own name.`;
    }
    labels.add(label.toLowerCase());

    const typeKnown = (PROOF_FIELD_TYPES as readonly string[]).includes(raw.type);
    if (!typeKnown) {
      errors[`${at}.type`] = 'A detail is either text (any code) or a phone number.';
    }

    let stored = value;
    if (value === '') {
      errors[`${at}.value`] = 'Enter what the client should see.';
    } else if (raw.type === 'phone') {
      const e164 = toE164(value);
      if (e164) stored = e164;
      else errors[`${at}.value`] = phoneProblem(value) ?? 'Enter a valid phone number.';
    } else if (hasControlCharacter(value) || value.length > PROOF_FIELD_LIMITS.value) {
      errors[`${at}.value`] =
        `Keep the value to ${PROOF_FIELD_LIMITS.value} characters, on one line.`;
    }

    if (hint.length > PROOF_FIELD_LIMITS.hint) {
      errors[`${at}.hint`] = `Keep the hint under ${PROOF_FIELD_LIMITS.hint} characters.`;
    }
    if (labelAr.length > PROOF_FIELD_LIMITS.label) {
      errors[`${at}.labelAr`] =
        `Keep the Arabic name under ${PROOF_FIELD_LIMITS.label} characters.`;
    }
    if (hintAr.length > PROOF_FIELD_LIMITS.hint) {
      errors[`${at}.hintAr`] = `Keep the Arabic hint under ${PROOF_FIELD_LIMITS.hint} characters.`;
    }

    fields.push({
      id: raw.id,
      label,
      type: raw.type as ProofFieldType,
      value: stored,
      enabled: raw.enabled ?? true,
      ...(hint === '' ? {} : { hint }),
      ...(labelAr === '' ? {} : { labelAr }),
      ...(hintAr === '' ? {} : { hintAr }),
    });
  });

  const first = Object.values(errors)[0];
  if (first) throw new FieldValidationError(first, errors);
  return fields;
}

/** Every detail as the CONSOLE edits it — hidden ones included, absent text as null. */
export function consolePayToFields(
  fields: readonly PayToField[],
): (ShownPayToField & { enabled: boolean })[] {
  return fields.map((field) => ({
    id: field.id,
    label: field.label,
    labelAr: field.labelAr ?? null,
    type: field.type,
    value: field.value,
    enabled: field.enabled,
    hint: field.hint ?? null,
    hintAr: field.hintAr ?? null,
  }));
}

/**
 * What a client is shown: the ENABLED details, and only where they apply — a
 * deposit method's on an offline route; a withdrawal method's always (0202).
 */
export function shownPayToFields(
  fields: readonly PayToField[],
  offline: boolean,
): ShownPayToField[] {
  if (!offline) return [];
  return fields
    .filter((field) => field.enabled)
    .map((field) => ({
      id: field.id,
      label: field.label,
      labelAr: field.labelAr ?? null,
      type: field.type,
      value: field.value,
      hint: field.hint ?? null,
      hintAr: field.hintAr ?? null,
    }));
}

/**
 * What a deposit records at filing: exactly what the client was shown, labels
 * included, so a later rename or a changed number never rewrites it.
 */
export function payToSnapshot(fields: readonly PayToField[], offline: boolean): PayToDetail[] {
  return shownPayToFields(fields, offline).map((field) => ({
    fieldId: field.id,
    label: field.label,
    ...(field.labelAr ? { labelAr: field.labelAr } : {}),
    type: field.type,
    value: field.value,
  }));
}

/** One cell for an export: `Send to: +96170123456; Name: OxShare`. */
export function formatPayToDetails(details: readonly PayToDetail[] | null | undefined): string {
  return (details ?? []).map((detail) => `${detail.label}: ${detail.value}`).join('; ');
}
