import { FieldValidationError } from '../errors/domain-errors';
import { toE164 } from '../profile/client-profile';

/**
 * The details a client gives with an OFFLINE deposit — the pure rules (0163).
 *
 * An offline method (`requires_proof`) is paid outside the platform: OMT, a bank
 * transfer, cash. The receipt proves a payment happened; what the desk also
 * needs is what IDENTIFIES it — the phone the money was sent from (often not the
 * client's own), a transfer code, a reference. Each method needs its own, so the
 * admin defines them per method (`payment_methods.proof_fields`) and the client
 * answers them when filing (`transactions.proof_details`).
 *
 * Three rules carry the design:
 *
 * - **An answer keeps the question it answered.** Each stored answer carries the
 *   field's LABEL as it read at filing. Renaming or deleting a field later never
 *   leaves an answer without its question — KYC 0148 is the lesson (the review
 *   printed "Custom Field 1790…" once a question outlived its name).
 * - **The server is the judge.** Only the method's ENABLED fields, as they stand
 *   at filing, are read; anything else a client sends is ignored. Refusals are
 *   keyed `details.<fieldId>` so the portal places each under its input.
 * - **A phone is stored as E.164**, through the profile's own `toE164`, so the
 *   desk can search it however it was typed.
 *
 * No Nest, no Drizzle: `schema.ts` types its columns with these, and the services
 * and the specs call the functions directly.
 */

export const PROOF_FIELD_TYPES = ['text', 'phone'] as const;
export type ProofFieldType = (typeof PROOF_FIELD_TYPES)[number];

/** One detail an offline method asks for, as the admin configured it. */
export interface ProofField {
  /** Permanent — `f_` + base-36, generated by the console. Answers are keyed by it. */
  id: string;
  /** What the client reads, and what the desk reads beside the answer. */
  label: string;
  type: ProofFieldType;
  required: boolean;
  /** Shown to clients. A hidden field is kept (and restorable) but never asked. */
  enabled: boolean;
  /** One line under the input, e.g. "The number the transfer was sent from". */
  hint?: string;
}

/** One answer, as filed — the label is the one the client was shown. */
export interface ProofDetail {
  fieldId: string;
  label: string;
  type: ProofFieldType;
  value: string;
}

/** What a client is shown for one field — no `enabled`, which is the desk's business. */
export interface AskedProofField {
  id: string;
  label: string;
  type: ProofFieldType;
  required: boolean;
  hint: string | null;
}

export const PROOF_FIELD_LIMITS = {
  /** Fields per method. */
  fields: 8,
  label: 60,
  hint: 160,
  /** A stored answer, after trimming. */
  value: 120,
  /** Keys a client may send at all, and the length of any one of them. */
  submittedKeys: 20,
  submittedValue: 200,
} as const;

export const PROOF_FIELD_ID_PATTERN = /^f_[0-9a-z]{6,16}$/;

/** A line break, tab or other control character — an answer is one plain line. */
function hasControlCharacter(text: string): boolean {
  for (let i = 0; i < text.length; i += 1) {
    const code = text.charCodeAt(i);
    if (code < 0x20 || code === 0x7f) return true;
  }
  return false;
}
const PHONE_MESSAGE =
  'Enter a complete phone number, including the country code (for example +961 70 123 456).';

export interface ProofFieldInput {
  id: string;
  label: string;
  type: string;
  required?: boolean;
  enabled?: boolean;
  hint?: string | null;
}

/**
 * The configuration as stored, or every refusal keyed `proofFields.<i>.<prop>`.
 *
 * Labels must differ (case-insensitively) because the desk reads them side by
 * side on one deposit, and ids must be unique because answers are keyed by them.
 */
export function normaliseProofFields(input: readonly ProofFieldInput[]): ProofField[] {
  const errors: Record<string, string> = {};
  if (input.length > PROOF_FIELD_LIMITS.fields) {
    errors['proofFields'] = `A method can ask for at most ${PROOF_FIELD_LIMITS.fields} details.`;
  }
  const ids = new Set<string>();
  const labels = new Set<string>();
  const fields: ProofField[] = [];

  input.forEach((raw, i) => {
    const at = `proofFields.${i}`;
    const label = raw.label.trim();
    const hint = raw.hint?.trim() ?? '';

    if (!PROOF_FIELD_ID_PATTERN.test(raw.id)) {
      errors[`${at}.id`] = 'This detail has an invalid id. Remove it and add it again.';
    } else if (ids.has(raw.id)) {
      errors[`${at}.id`] = 'Two details share one id. Remove one and add it again.';
    }
    ids.add(raw.id);

    if (label === '' || label.length > PROOF_FIELD_LIMITS.label) {
      errors[`${at}.label`] = `Name each detail in 1 to ${PROOF_FIELD_LIMITS.label} characters.`;
    } else if (labels.has(label.toLowerCase())) {
      errors[`${at}.label`] = `Two details are called “${label}”. Give each its own name.`;
    }
    labels.add(label.toLowerCase());

    if (!(PROOF_FIELD_TYPES as readonly string[]).includes(raw.type)) {
      errors[`${at}.type`] = 'A detail is either text (any code) or a phone number.';
    }
    if (hint.length > PROOF_FIELD_LIMITS.hint) {
      errors[`${at}.hint`] = `Keep the hint under ${PROOF_FIELD_LIMITS.hint} characters.`;
    }

    fields.push({
      id: raw.id,
      label,
      type: raw.type as ProofFieldType,
      required: raw.required ?? false,
      enabled: raw.enabled ?? true,
      ...(hint === '' ? {} : { hint }),
    });
  });

  const first = Object.values(errors)[0];
  if (first) throw new FieldValidationError(first, errors);
  return fields;
}

/**
 * What a client is asked: the ENABLED fields, and only while the method is paid
 * outside the platform. A gateway method's configuration is inert — kept, so
 * re-ticking "paid outside the platform" restores it, but never asked.
 */
export function askedProofFields(
  fields: readonly ProofField[],
  requiresProof: boolean,
): AskedProofField[] {
  if (!requiresProof) return [];
  return fields
    .filter((field) => field.enabled)
    .map((field) => ({
      id: field.id,
      label: field.label,
      type: field.type,
      required: field.required,
      hint: field.hint ?? null,
    }));
}

/**
 * The client's answers, judged against the fields the method asks NOW.
 *
 * Returns them in the method's order, each with its label as asked. A required
 * field left empty, a text with control characters or over the limit, and a
 * phone that is not a complete international number are refused, keyed
 * `details.<fieldId>`. An optional field left empty is omitted; a key that names
 * no asked field is ignored (the admin may have hidden it while the page was open).
 */
export function readProofDetails(
  fields: readonly ProofField[],
  requiresProof: boolean,
  submitted: unknown,
): ProofDetail[] {
  const raw = submitted ?? {};
  if (typeof raw !== 'object' || Array.isArray(raw)) {
    throw new FieldValidationError('The details could not be read.', {
      details: 'The details could not be read.',
    });
  }
  const entries = Object.entries(raw as Record<string, unknown>);
  if (
    entries.length > PROOF_FIELD_LIMITS.submittedKeys ||
    entries.some(
      ([, value]) => typeof value !== 'string' || value.length > PROOF_FIELD_LIMITS.submittedValue,
    )
  ) {
    throw new FieldValidationError('The details could not be read.', {
      details: 'The details could not be read.',
    });
  }

  const errors: Record<string, string> = {};
  const answers: ProofDetail[] = [];
  for (const field of askedProofFields(fields, requiresProof)) {
    const given = Object.hasOwn(raw, field.id) ? (raw as Record<string, string>)[field.id] : '';
    const text = (given ?? '').trim();
    const at = `details.${field.id}`;

    if (text === '') {
      if (field.required) errors[at] = `${field.label} is required.`;
      continue;
    }
    if (field.type === 'phone') {
      const e164 = toE164(text);
      if (!e164) {
        errors[at] = PHONE_MESSAGE;
        continue;
      }
      answers.push({ fieldId: field.id, label: field.label, type: field.type, value: e164 });
      continue;
    }
    if (hasControlCharacter(text) || text.length > PROOF_FIELD_LIMITS.value) {
      errors[at] =
        `${field.label} must be at most ${PROOF_FIELD_LIMITS.value} characters, on one line.`;
      continue;
    }
    answers.push({ fieldId: field.id, label: field.label, type: field.type, value: text });
  }

  const first = Object.values(errors)[0];
  if (first) throw new FieldValidationError(first, errors);
  return answers;
}

/** One cell for an export: `Phone number: +96170123456; Code: 88213`. */
export function formatProofDetails(details: readonly ProofDetail[] | null | undefined): string {
  return (details ?? []).map((detail) => `${detail.label}: ${detail.value}`).join('; ');
}
